### ISSUE TITLE
Ambientes de Desenvolvimento e Teste | Jéssica e Irineu

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#12]
Preparar ambientes de desenvolvimento e teste.

**Comment by lucaszwk** [comment]
Minhas sugestões:

Ambiente de desenvolvimento:
- **Visual Studio Code**: https://code.visualstudio.com
- **Cordova Tools Extension for VS Code**: https://github.com/Microsoft/vscode-cordova
- **Git Kraken**: http://www.gitkraken.com

Ambiente de teste:
- Smartphone com Android versão Lollipop

**Comment by irineulemos** [comment]
Lucas eu acredito que as suas sugestões são válidas e devemos segui-lá mas gostaria de acrescentar no ambiente de desenvolvimento o:
- **Sublime:** https://www.sublimetext.com/3

**Comment by lucaszwk** [comment]
O Sublime também é uma boa opção.

**Comment by jessicaLPII** [comment]
As ferramentas, plugins e extensões baixados e instalados para desenvolvimento foram:
- Visual Studio Code
- Git Kraken
- Sublime
- Ionic 1
- Cordova
- Node JS
