### ISSUE TITLE
Protótipo de tela | Jéssica e Irineu

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#13]
Criar protótipo da tela de login.

Testar as ferramentas de prototipação disponíveis para identificar a melhor.

Opções:
**Ionic Creator:** https://creator.ionic.io
**Ionic Play:** http://play.ionic.io
**Ionic Lab:** http://lab.ionic.io

**Comment by jessicaLPII** [comment]
Utilizamos o Ionic Play. Segue o protótipo da tela de login.

![prototipo-login](https://cloud.githubusercontent.com/assets/10115850/13731090/dd476f10-e93f-11e5-86b1-034255c17176.png)
