### ISSUE TITLE
Visão do Produto | Irineu e Lucas

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#2]
Criar documento de visão do produto com base no edital da maratona tecnológica.

Pesquisar um modelo apropriado na internet.

Instalar o Git Kraken e subir o arquivo pro repositório de documentos (docs).

Pedir ajuda ao Lucas pra configurar e usar o Git Kraken pela primeira vez.

Tempo para conclusão da atividade:
Estimado: 4h
Real: 4h

**Comment by irineulemos** [comment]
Finalizei e publiquei o documento de visão, demorei exatamente 4 horas para elaborar.

O lucas irá revisar o documento e adicionar ou corrigir algo que achar pertinente.

**Comment by lucaszwk** [comment]
Adicionei capa e sumário. Removi o recuo dos parágrafos também. Só falta revisar o conteúdo.

**Comment by lucaszwk** [comment]
Documento revisado e atualizado no repositório. Tarefa concluída.
