### ISSUE TITLE
Cartões com estórias | Letícia e David

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#20]
Preparar cartões com o esboço das estórias do projeto.

Também levar cartões em branco caso seja necessário.

**Comment by lefernandesrocha** [comment]
E01 – Realizar login

Como um usuário do aplicativo, desejo realizar o meu login, informando usuário e senha para ter acesso a todas as funcionalidades do aplicativo.

ET01 -  Deve-se verificar se o campo login e senha não estão vazios.
ET02 -  O campo login deve aceitar apenas caracteres numéricos (0-9);
ET03 – O campo senha deve possuir no mínimo 8 caracteres;
ET04 - O campo senha deve possuir caracteres alfabéticos (a-z), caracteres numéricos (0-9);
ET05 - Caso seja digitada a senha incorreta 3 vezes consecutivas a conta do usuário passará para o estado de bloqueada temporariamente.

**Comment by lefernandesrocha** [comment]
ATUALIZAÇÃO:

E01 – Realizar login

Como um usuário do aplicativo, desejo realizar o meu login, informando usuário e senha para ter acesso a todas as funcionalidades do aplicativo.

ET01 -  Deve-se verificar se o campo login e senha não estão vazios.
ET02 – O campo senha deve possuir no mínimo 8 caracteres;
ET03 - Caso seja digitada a senha incorreta 3 vezes consecutivas a conta do usuário passará para o estado de bloqueada temporariamente.
ET04 – O login só poderá ser realizado se o campo for equivalente a matricula digitada.
