### ISSUE TITLE
Estória + casos de teste do cadastro de usuário | Letícia e Michel

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#22]
Criar estória da tela de cadastro de usuário.

Definir os casos de teste.

Informar o número de horas gastas nesta atividade.

Estimativa: 1 hora

**Comment by lucaszwk** [comment]
**E02 – Cadastrar Usuário**

Eu, como aluno da UVV ainda não cadastrado no aplicativo, desejo me cadastrar informando os seguintes dados: nome completo, senha, email, matrícula, endereço completo com ponto de referência (opcionalmente usar localização atual), telefone celular, para após o cadastro poder acessar o aplicativo. Durante o cadastro é necessário informar se desejo oferecer carona, caso sim, é necessário informar o modelo e a cor do carro.

**Casos de Teste**

ET05 – Verificar se a matrícula é válida;
ET06 - O campo senha deve possuir no mínimo 8 caracteres;
ET07 – Verificar se todos os campos estão preenchidos;
ET08 – Verificar se o campo telefone possui 11 dígitos;
ET09 - O campo login deve possuir apenas números;

**Comment by lefernandesrocha** [comment]
Tempo estimado: 1 hora
Tempo gasto: 1 hora
