### ISSUE TITLE
Pesquisa sobre google play | Ewerton, Rafael e João

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#23]
Pesquisar os requisitos, prazos e preços pra colocar o aplicativo na Google Play.

Postar as informações encontradas nesta tarefa.

**Comment by rafaelgude** [comment]
Estas são as informações que creio que precisamos.
Se estiver faltando alguma informação, me avise.

**Comment by rafaelgude** [comment]
## SOBRE O REGISTRO

Primeiro é necessário ter uma conta do Google e ir neste link: https://play.google.com/apps/publish/signup/

Ao entrar, logar com a conta Google e depois Aceitar o Contrato de Desenvolvedor, que é cobrado o valor de $25 (em torno de R$90) como taxa de registro. O método de pagamento vai depender da conta Google de quem for aceitar o Contrato de Desenvolvedor, a princípio é apenas Cartão de Crédito. Para adicionar mais métodos tem que ir na conta Google e colocar as informações lá. O registro pode demorar até 48 horas.
Depois preencher os detalhes da conta, incluindo o Nome do Desenvolvedor.

## **SOBRE O APLICATIVO**

Para adicionar um aplicativo, é necessário ir em "Adicionar novo aplicativo" no Console de Desenvolvedor e preencher as informações:
Obs.: Estas abaixo são as informações principais, depois é possível detalhar com mais informações.

**Fazer o Upload de Recursos**
• _Arquivo APK:_ o tamanho máximo suportado por um único .APK é 100MB. Podem-se usar arquivos de expansão para fazer o upload de recursos adicionais, como imagens. Se não houver compatibilidade com todos os dispositivos desejados com um APK, pode-se fazer o upload de vários APKs na mesma listagem de aplicativo para cada configuração diferente de dispositivo desejada.
• _Capturas de tela:_ são necessárias duas capturas de tela, e as seis capturas adicionais disponíveis são opcionais.

**Detalhes de Entrada**
• _Idioma:_ para indicar o idioma do aplicativo. 
• _Título:_ o nome do aplicativo que aparecerá no Google Play. Pode-se adicionar um por idioma.
• _Descrição:_ a descrição visível do aplicativo. Há um limite de 4 mil caracteres para esse campo.
• _O que há de novo nesta versão?:_ adicione notas sobre alterações específicas às versões publicadas do seu aplicativo.
• _Tipo de aplicativo:_ escolher se o aplicativo é do tipo “Aplicativos” ou “Jogos”.
• _Categoria:_ selecionar uma categoria para o aplicativo.
Opções de publicação
• _Locais:_ são os locais em que o aplicativo poderá ser distribuído. Selecionar os locais um por um ou habilitar “Todos os locais atuais e futuros”.

**Dados de contato**
• Precisa-se escolher um canal de suporte para o aplicativo: website, e-mail ou telefone.
• Os usuários do Google Play poderão ver essas informações.
• Podem-se oferecer vários canais de suporte.

## **OUTRAS INFORMAÇÕES**

• A Conta de Desenvolvedor não tem expiração.
• É possível colocar vários aplicativos usando a mesma conta.
• Não é preciso pagar nenhuma taxa para colocar aplicativos.
• A taxa de $25 é única. É preciso ser paga apenas para evitar spam.
• Podem-se adicionar outros usuários (contas do Google) para usar o Console de Desenvolvedor, gerenciando as permissões dos mesmos.

Caso alguém queira ler o Contrato de distribuição do desenvolvedor do Google Play, aqui está o link: 
https://play.google.com/intl/ALL_br/about/developer-distribution-agreement.html

Adicionar mais métodos de pagamento à Conta do Google: https://support.google.com/googleplay/answer/4646404?co=GENIE.Platform%3DDesktop&hl=pt-BR&oco=0

Estas informações no Word: 
[Colocando o Aplicativo no Google Play.docx](https://github.com/Me-Leva/docs/files/194237/Colocando.o.Aplicativo.no.Google.Play.docx)

**Comment by lucaszwk** [comment]
Existe algum desconto para estudantes ou projetos open source?

**Comment by rafaelgude** [comment]
Mandei um e-mail de contato para a Google americana (porque o setor em que fui não tinha suporte para o Brasil), perguntando sobre os descontos, porque não achei na internet sobre isso. Me deram um prazo de 2 dias úteis para darem a resposta.

E ali em cima corrigi uma informação sobre o método de pagamento, não é só apenas cartão de crédito, porém pelo visto o cartão de crédito/débito é o mais viável para o Brasil.

**Comment by rafaelgude** [comment]
Já recebi a resposta.
Eles disseram que não há desconto para ningúem. Todos desenvolvedores tem que pagar a taxa de $25.
