### ISSUE TITLE
Protótipos de tela | Jéssica

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#25]
Criar protótipos de acordo com as estórias das seguintes telas:
- cadastro de usuário
- tela principal
- pedir carona

Subir os protótipos pro repositório de documentos.

Informar as horas gastas nesta atividade.

Estimativa: 4 horas

**Comment by jessicaLPII** [comment]
Relizada: 5h
Fator de atraso: Problemas com redimensionamento e posicionamento de imagem.

**> Tela de Cadastro**
![prototipo-cadastro](https://cloud.githubusercontent.com/assets/10115850/14060355/e0b3b7f2-f340-11e5-965d-711364eac319.png)

**>Tela Principal**
![prototipo-tela-principal](https://cloud.githubusercontent.com/assets/10115850/14060384/e1d4bcca-f341-11e5-8074-22a0e94320f2.png)

**> Tela Pedir Carona**
**\- Origem**
![prototipo-pedir-carona-origem](https://cloud.githubusercontent.com/assets/10115850/14060386/f08121dc-f341-11e5-9496-38112c19bc70.png)

**-Destino**
![prototipo-pedir-carona-destino](https://cloud.githubusercontent.com/assets/10115850/14060389/f5da65a8-f341-11e5-8305-a4ac9d944b0f.png)
