### ISSUE TITLE
Estória + casos de teste da tela principal | Letícia e Michel

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#26]
Criar estória da tela principal.

Definir os casos de teste.

Informar o número de horas gastas nesta atividade.

Estimativa: 1 hora

**Comment by lucaszwk** [comment]
**E05 – Selecionar Aluno / Motorista**

Eu, como aluno já cadastrado e logado no aplicativo, desejo selecionar na tela principal se quero pedir carona ou oferecer carona.

**Casos de Teste**

ET15 – Ao selecionar a opção “Pedir Carona”, deverá abrir a tela para que o aluno preencha os campos origem, destino e a quantidade de vagas necessárias.
ET16 – Ao selecionar a opção “Oferecer Carona”, deverá abrir a tela para que o motorista possa selecionar os bairros de sua rota para visualizar os solicitantes que estão disponíveis naqueles bairros.

**Comment by lefernandesrocha** [comment]
Tempo estimado: 1h
Tempo gasto: 40 minutos
