### ISSUE TITLE
Estória + casos de teste da tela pedir carona | Letícia e Michel

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#27]
Criar estória da tela pedir carona.

Definir os casos de teste.

Informar o número de horas gastas nesta atividade.

Estimativa: 1 hora

**Comment by lucaszwk** [comment]
**E06 – Pedir Carona**

Eu, como aluno cadastrado no sistema, desejo solicitar uma carona informando minha localização atual, meu destino e a quantidade de pessoas que vão comigo. Após 20 minutos, a minha solicitação deve ser cancelada, caso eu não tenha retorno.

**Casos de Teste**

ET17 – Verificar se os campos de origem e destino estão preenchidos.
ET18 – Verificar se, após 20 minutos, a solicitação será cancelada.
ET19 – Verificar se o número de vagas é no mínimo 1 e no máximo 4.
ET20 – Os campos de origem e destino não podem ser iguais.

**Comment by lefernandesrocha** [comment]
Tempo estimado: 1h
Tempo gasto: 1h
