### ISSUE TITLE
Teste das telas implementadas | David

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#28]
Testar as seguintes telas:
- cadastro de usuário
- tela principal
- pedir carona

Verificar se as funcionalidades implementadas estão de acordo com as estórias das telas.

Registrar os testes na planilha apropriada.

Informar o número de horas gastas nesta atividade.

Estimativa: 2 horas

**Comment by jessicaLPII** [comment]
Tarefa concluída em 2 horas.
