### ISSUE TITLE
Gestão de Projetos | Michel

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#3]
Criar apresentação sobre a gestão de projetos no nível G do MPSBR.

Colocar o arquivo da apresentação no repositório de documentos.

Tempo estimado: 4h

**Comment by michelventurin** [comment]
[MPSBR x SCRUM.pptx](https://github.com/Me-Leva/docs/files/142906/MPSBR.x.SCRUM.pptx)

O apresentação está concluída, com a pendência apenas de definir um template para o documento que será realizado hoje (23/02) durante a aula.
Irei tirar algumas dúvidas com a Professora Susileia durante a aula quanto ao documento.
Tempo gasto: 3 horas.
