### ISSUE TITLE
Implementar a tela pedir carona | Irineu

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#32]
Implementar a tela pedir carona de acordo com o protótipo e a estória criadas para tal.

Protótipo: #25 

Estória: #27 

Informar o número de horas gastas nesta atividade.

Estimativa: 8 horas

**Comment by irineulemos** [comment]
**Pontos realizados:**
- Correção das mensagens de erro da tela de login devido a mudança de banco;
- Criação da tela pedir carona;
- Criação de nova rota de navegação;
-  Inclusão de novo controller;
- adaptação de layout.

**## Pontos ainda a serem realizados:**
- Falta fazer a validação do campo de destino ou origem (depende da seleção do usuário pois os outros são preenchidos automaticamente);
- Falta incluir o cancelamento da busca após 20 minutos (coloquei um timer na tela mas falta definir como será o cancelamento em si) e colocar um relógio com o tempo na tela com tempo de busca.
- E algum outro ponto que queriam melhorar.

Tempo Estimado : 8 horas.
Tempo Gasto: 6 horas.

**Comment by jessicaLPII** [comment]
Correções Realizadas. Tarefa concluída em 6 horas.
