### ISSUE TITLE
Pesquisa sobre documentação | Diego, Cleiton, Bruno e Leandro

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#33]
Pesquisar sobre a documentação exigida pela maratona tecnológica.

Postar as informações encontradas nesta tarefa.

**Comment by Dimaco** [comment]
# Requisitos de Documentação e Modelagem

## A documentação do aplicativo deve ter:

### Uma capa com:

O nome do aplicativo.

### Contra Capa com:

O nome de cada componente do grupo.

### Introdução:

Texto descrevendo o domínio do problema e as funcionalidades a 
serem desempenhadas pelo aplicativo.

### Construção:

Nessa parte deverá ser descrito a modelagem e as características 
técnicas e tecnológicas do seu aplicativo: 
- Técnicas e algoritmos.
- Recursos tecnológicos.
- Diagrama de casos de uso, descrição resumida dos casos de uso, 
  diagrama  de  classes  de  projeto,  diagrama  de  componentes  e 
  diagrama de implantação.

**Comment by lucaszwk** [comment]
A documentação deve ser entregue em qual data?
Quantas cópias devem ser entregues?
