### ISSUE TITLE
Elaborar relatório de produtividade | Jéssica

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#35]
Elaborar planilha de produtividade com as seguintes informações:
- horas estimadas / realizadas por pessoa
- horas estimadas / realizadas por sprint
- percentual de desvio
- gráficos de produtividade

Subir a planilha pro repositório de documentos.

Informar a quantidade de horas gastas nesta atividade.

Estimado: 8 h

**Comment by jessicaLPII** [comment]
Tarefa concluída em 4 horas.
