### ISSUE TITLE
Criar protótipo de tela | Michel

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#38]
Criar protótipos de tela pras seguintes estórias:
- listar / pesquisar pedidos de carona
- oferecer carona

Informar o número de horas gastas nesta atividade.

Estimativa: 3 horas

**Comment by michelventurin** [comment]
Protótipos criados, aprovados pela equipe e incluídos na pasta "prototipos" do reservatório.
Tempo gasto: 2 horas
