### ISSUE TITLE
Completar o Grupo

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#4]
[Equipe Maratona Tecnológica.pptx](https://github.com/Me-Leva/docs/files/146817/Equipe.Maratona.Tecnologica.pptx)

Convidar mais pessoas pro grupo a fim de atender o requisito da maratona tecnológica: 15 integrantes.

Realizar a inscrição do grupo na maratona.

**Comment by lucaszwk** [comment]
@jessicaLPII com quem nós já podemos contar? Precisa de ajuda pra chamar mais pessoas?

**Comment by jessicaLPII** [comment]
@lucascarlos ontem eu consegui fechar 15 pessoas, nas quais 4 delas estão pendentes de confirmação. Essas pessoas são os 3 indicados da Letícia, porque dependem da resposta do Cristiano (que eu acho que será irredutível) e 1 indicado do David.

A minha idéia é fechar essa lista como está e depois alteramos pra uma próxima sprint quando fizermos as substituições definitivas.

**Comment by lefernandesrocha** [comment]
@lucascarlos  e @jessicaLPII Tenho duas pessoas que querem entrar no grupo, mas para isso preciso que todos do grupo concordem com a inclusão deles. Um é o Leandro do 3º período e o outro é um menino do 7º período. 
Se todos concordarem ja vou adicioná-los no grupo do whats

**Comment by jessicaLPII** [comment]
Eu concordo com a inclusão deles, mas acho que devíamos fazer uma reunião com todos primeiro pra explicar tudo e fazer a redistribuição das funções e depois adicionamos no grupo, pra eles não caírem de paraquedas no projeto "em andamento" sem informação nenhuma.

**Comment by lucaszwk** [comment]
Concordo. Precisamos de uma reunião pra explicar como o projeto vai funcionar.

**Comment by jessicaLPII** [comment]
Planilha de Inscrição Enviada!

Segue a lista completa dos integrantes da equipe 5 da Maratona Tecnológica.

Lucas Carlos (líder) - lucascarlos@prontonmail.com  - SI7N
Jéssica Lima (líder) - jessicamendes.info@gmail.com - SI7N
Irineu Lemos - irineuljr@gmail.com - SI7N
Michel Venturin - michelventurin@gmail.com - SI7N
David Eler - david.eler@hotmail.com - SI7N
Joelma Menezes - joelmatg@hotmail.com - SI7N
Josicleiton Souza - cleitonvip.space@gmail.com - SI7N
Alexandre Nickel - nickeljunior@htomail.com - SI6N
Leandro Cesar    - llmanutencao@bol.com.br - SI3N
João Carlos - miss.joaocarlos@hotmail.com - SI1N
João Lacorte - lacorte1005@gmail.com - SI1N
Rafael Gude - gudemvl@hotmail.com - SI1N
Ryan Usberti - ryan@rusberti.com - SI5N
Ewerton Bertulani  - bertulani.ewerton@gmail.com - SI1N
Diego Maia - diego.maia.costa@hotmail.com - SI2N
Bruno Martins - brunodaumartin@hotmail.com - SI2N
Fernando Lozer - flichtenheld@gmail.com - SI7N
Letícia Fernandes - lefernandesrocha@gmail.com - SI7N

Total = 18 pessoas.

**Comment by lucaszwk** [comment]
Fernando Lozer Lichtenheld - flichtenheld@gmail.com
