### ISSUE TITLE
Redigir estórias e casos de teste | Letícia

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#40]
Criar as estórias e os casos de teste das seguintes funcionalidades:
- listar / pesquisar pedidos de carona
- oferecer carona
- aceitar / recusar carona oferecida

Registrar as estórias e os casos de teste nas planilhas apropriadas.

Informar o número de horas gastas nesta atividade.

Estimativa: 3 horas

**Comment by lefernandesrocha** [comment]
Tempo estimado: 3 horas
Tempo gasto: 3 horas

Estórias:

E08 – Buscar carona                           **(8 pontos)**
Eu como aluno motorista da UVV entro no aplicativo para buscar os alunos que desejam carona, filtrando os bairros que irei passar.
ET22 – Caso nenhum filtro seja selecionado, o aplicativo deverá exibir todos as caronas disponíveis no sistema
ET23 – Caso seja aplicado algum filtro, o aplicativo deverá exibir apenas as caronas disponíveis de acordo com os filtros aplicados.

E09 – Confirmar oferecimento de carona                **(2 pontos)**
Eu como aluno motorista já cadastrado confirmo o oferecimento de uma carona que foi buscada antecipadamente.
ET 24 – Ao confirmar o oferecimento de uma carona, o aluno solicitante não poderá aparecer na tela principal de busca de caronas.
ET25 – Uma mensagem deverá ser enviada para o solicitante informando o oferecimento da carona.

E10 – Aceitar carona/Rejeitar carona                  **(8 pontos)**
Eu como aluno da UVV já cadastrado, posso aceitar ou não uma carona que foi oferecida para mim. Ao aceitar ou rejeitar uma carona meu nome deverá sair da lista.
ET26 – Ao aceitar a carona, o status da carona deixa de ser disponível, consequentemente não poderá mais aparecer na tela inicial de busca de carona.
ET27 – Ao recusar a carona, o status da carona deixa de ser disponível, consequentemente não poderá mais aparecer na tela inicial de busca de carona.
ET28 – Ao aceitar a carona, uma mensagem deverá ser enviada para o motorista confirmando a carona.
