### ISSUE TITLE
Testar funcionalidades implementadas | David

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#41]
Testar as seguintes funcionalidades implementadas:
- listar / pesquisar pedidos de carona
- oferecer carona
- aceitar / recusar carona oferecida

Registrar os resultados na planilha apropriada.

Informar o número de horas gastas nesta atividade.

Estimativa: 2 horas

**Comment by jessicaLPII** [comment]
Tarefa não concluída devido falta de entrega do desenvolvimento.
