### ISSUE TITLE
Criar estória da tela de histórico de caronas | Letícia

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#53]
Criar estória da tela de histórico de carona.

Listar somente caronas ativas (exibir nome e telefone)
Ordenar pela carona mais recente
Ao clicar no nome do motorista, listar as pessoas presentes no carro (caroneiros) e exibir seus respectivos nomes e telefones.

Informar o número de horas gastas nesta atividade.

Tempo Estimado: 1 hora

**Comment by lefernandesrocha** [comment]
Eu como aluno da UVV já cadastrado, desejo visualizar meu histórico de caronas ativas, ordenadas a partir da carona mais recente. Desejo também visualizar detalhes da carona (pessoas presentes no carro e seus respectivos nomes e telefones).

Tempo Estimado: 1 hora
Tempo gasto: 30 minutos
