### ISSUE TITLE
Backlog de Análise | Letícia

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#6]
Criar lista dos itens de backlog do produto relacionados à área de análise.

Comentar esta tarefa com a lista para que todos possam ver.

**Comment by susilea** [comment]
Senhores

o backlog que iremos montar inicialmente é apenas o backlog do produto. Não sei o que pensaram quando criaram backlog para análise e testes. As atividades de análise e testes estão "dentro" das atividades de produto.

**Comment by lucaszwk** [comment]
Susiléa, nós dividimos o backlog do produto em algumas áreas pra facilitar a divisão de tarefas. Assim que as tarefas forem concluídas, eu vou reunir tudo num único backlog do produto.

**Comment by susilea** [comment]
Certo,

porém, acredito que vocês não consigam definir backlogs diferentes do
produto ainda nesta etapa. Foquem no backlog do produto.

Susi

Em 1 de março de 2016 10:15, Lucas Carlos notifications@github.com
escreveu:

**Comment by DavidEler** [comment]
Boa Noite,
Conforme alinhado com a Susi não será necessário realizar essa ação esse momento.

Posteriormente será necessário realizar algumas tarefas:

Elaborar diagrama de classe
Descreve o ambiente
