### ISSUE TITLE
Tratamento de Erros | Lucas

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#64]
Exibir para o usuário as mensagens de:
     - Falha na Internet
     - Falha na Requisição
     - Esperar do oferecimento de carona

Tempo Estimado: 8h

**Comment by lucaszwk** [comment]
Inseri comentários no código e corrigi as mensagens de validação até a linha 770.

Ainda faltam 230 linhas.

Gastei 4 horas até agora.

**Comment by lucaszwk** [comment]
Tarefa concluída.
1150 linhas de código comentadas.
Mensagens de erro corrigidas e padronizadas.

Tempo gasto: 6 horas
