### ISSUE TITLE
Backlog de Desenvolvimento Front-end | Irineu e Jéssica

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#7]
Criar lista dos itens de backlog do produto relacionados à área de desenvolvimento front-end.

Comentar esta tarefa com a lista para que todos possam ver.

**Comment by jessicaLPII** [comment]
[Backlog Front-End.pptx](https://github.com/Me-Leva/docs/files/149908/Backlog.Front-End.pptx)

Não sabíamos como essa lista deveria ser apresentada, então fizemos em forma de ppt mesmo. Uma breve descrição sobre os itens que deverão ter em cada tela.

Tempo estimado: 2h
Tempo real gasto: 1h

**Comment by lucaszwk** [comment]
Conteúdo da apresentação backlog de desenvolvimento front-end:

**Tela Inicial: Login**
- logotipo
- campo de login
- campo de senha
- link para cadastro

**Tela Principal**
- logotipo
- menu principal
- buscar caronas
- minhas caronas
- mostrar caronas oferecidas
- botão ‘aceitar carona’
- mostrar quantidade de recomendações

**Tela de Cadastro**
- logotipo
- formulário de cadastro
- campo nome
- campo matrícula
- campo endereço
- campo telefone
- botão ‘cancelar’
- botão ‘salvar’
- redirecionamento para a tela de login
- campo ‘inserir foto’

**Tela Busca de Caronas**
- botão ‘mostrar caronas disponíveis’
- filtro por bairro
- botão ‘filtrar’
- botão ‘oferecer carona’
- campo de vagas disponíveis

**Tela Minhas Caronas**
- lista de caronas recentes
- botão ‘recomendar carona’

**Comment by lefernandesrocha** [comment]
Segue a versão corrigida pela susi do novo backlog de front-end:

**Login**
• efetuar login
• efetuar logoff
• recuperar senha
• cadastrar usuário (buscar endereço através do maps)
• validar usuário*
• trocar senha

**Tela Principal**
• buscar caronas
• mostrar histórico de caronas
• mostrar caronas disponíveis
• aceitar carona
• mostrar quantidade de recomendações da carona

**Tela Busca de Caronas**
• listar caronas disponíveis
• filtrar caronas disponíveis por bairro
• oferecer carona
• mostrar vagas disponíveis
• exibir caronas por geolocalização*

**Tela Minhas Caronas**
• listar caronas recentes
• recomendar carona
