### ISSUE TITLE
Refazer o Tratamento de Erros | Lucas

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#70]
Tratar os erros de forma completa. 
obs.: consultar o Irineu para realizar esta tarefa.

Tempo estimado: 4 horas.

**Comment by lucaszwk** [comment]
As principais funcionalidades do sistema possuem tratamento de erro.

A maioria das requisições exibe uma mensagem informativa em caso de falha.

Apenas os erros genéricos do console persistem por alguma razão desconhecida.

Tempo gasto: 4 horas
