### ISSUE TITLE
Criar Estórias para 'Esqueci Minha Senha' e 'Alterar Dados de Cadastro'  | Letícia

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#75]
Escrever Estórias. Tempo Estimado: 1 hora.

**Comment by lefernandesrocha** [comment]
Tempo gasto 1h

E10 – Alterar dados do cadastro
Eu como aluno da Universidade Vila Velha, desejo alterar os dados que foram inseridos no ato do cadastro. Os dados que não podem ser alterados são: nome e matrícula.
ET19 - Verificar se o campo telefone possui 11 dígitos;
ET20 - Verificar se todos os campos estão preenchidos;
ET21 - O campo senha deve possuir no mínimo 8 caracteres;
ET22 – Realizar a tentativa de alterar um campo que não é permitido;

E11 – Esqueci minha senha
Como aluno da Universidade Vila Velha, devidamente cadastrado no sistema, desejo recuperar minha senha para utilização do aplicativo. A redefinição da senha deverá acontecer pelo email, cujo título será “Redefinição de senha - MeLeva” , e o corpo do email será: "Prezado(a) Usuário(a)

Conforme solicitado, segue sua senha de acesso ao Aplicativo MeLeva!

Sua senha foi redefinida para: XXXXXXXX.

Ao acessar o aplicativo, favor selecionar a opção 'Alterar Cadastro' e realizar a troca de senha, assim você poderá escolher uma de sua preferência. Também poderá alterar seus dados cadastrais, incluindo o e-mail para recebimento de nova senha.

Importante: esta é uma mensagem automática e não deve ser respondida.
Política de Segurança: O MeLeva! nunca envia arquivos executáveis ou solicitação de dados pessoais. Para sua segurança mantenha atualizado o antivírus do seu computador.

Atenciosamente,
Equipe MeLeva!"

ET23 – Verificar de o email está cadastrado;
ET24 – Verificar se o campo email está em branco;
