### ISSUE TITLE
Backlog de Desenvolvimento Back-end | Lucas

### ISSUE THREAD

**Issue by lucaszwk** [Me-Leva/docs#8]
Criar lista dos itens de backlog do produto relacionados à área de desenvolvimento back-end.

Comentar esta tarefa com a lista para que todos possam ver.

**Comment by lucaszwk** [comment]
**Documentos**
- criar modelo do banco de dados
- validar modelo com o restante do grupo
- criar modelo da aplicação back-end
- validar modelo com o restante do grupo

**Banco de Dados**
- criar banco de dados
- tornar o banco acessível à aplicação
- implementar coleções de documentos

**Aplicação**
- criar estrutura básica da aplicação back-end
- implementar acesso ao banco de dados
- implementar API padrão RESTful
- implementar segurança
- tornar aplicação back-end acessível ao front-end

**Comment by lefernandesrocha** [comment]
Segue abaixo a  versão corrigida do novo backlog de back-end:

**Documentos**
• criar modelo do banco de dados
• criar modelo da aplicação back-end

**Banco de Dados**
• criar banco de dados
• tornar o banco acessível à aplicação
• implementar coleções de documentos

**Aplicação**
• criar o projeto back-end
• criar o projeto front-end
• configurar acesso ao banco de dados
• implementar API padrão RESTful
• implementar segurança*
• tornar aplicação back-end acessível ao front-end
