### ISSUE TITLE
Implementar Geolocalização | Lucas

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#80]
Capturar endereço de onde o solicitante está. Tempo Estimado: 8 horas

**Comment by lucaszwk** [comment]
Adicionei um botão na tela "pedir carona" pra obter as coordenadas do usuário.

O plugin de geolocalização foi implementado com sucesso.

O próximo passo é utilizar as coordenadas pra obter a cidade e o bairro do usuário.

**Comment by lucaszwk** [comment]
A função de geolocalização foi implementada com sucesso.

O bairro e a cidade do usuário são obtidos através das coordenadas do dispositivo.

A precisão das coordendas depende das condições do GPS ou da rede.

Tempo gasto: 8 horas
