### ISSUE TITLE
Criar Protótipos | Michel

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#81]
Criar protótipos das telas:
- Recomendar motorista (atualizar tela de histórico de caronas).
- Geolocalização
- Ofertar carona (atualizado com a mensagem exibindo número de caronas oferecidas e número de recomendações).
  Tempo Estimado: 2 horas.

**Comment by michelventurin** [comment]
Tarefa concluída em 1:30 hrs.
