### ISSUE TITLE
Criar Estórias para 'Recomendar Motorista', 'Geolocalização' e 'Visualizar Recomendação Motorista' | Letícia

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#82]
Escrever as estórias das funcionalidades 'Recomendar Motorista', 'Geolocalização' e 'Visualizar Recomendação Motorista'.
Tempo Estimado: 1 hora.

**Comment by lefernandesrocha** [comment]
Tempo gasto 1h

E04 – Pedir carona (8 pontos)
Eu como aluno cadastrado no sistema desejo sinalizar uma carona, informando minha origem ou destino e a quantidade de pessoas. A origem/destino poderá ser informada através da geolocalização.
Após 20 minutos a minha solicitação deverá ser cancelada, caso eu não tenha retorno.

E12 – Recomendar motorista    (5 pontos)
Eu como aluno solicitante da UVV desejo recomendar, ou não um motorista que peguei carona anteriormente. Cada recomendação contará “+1” ponto no total das recomendações daquele motorista. Para recomendar um motorista, é necessário acessar a tela de Histórico de caronas.

E13 – Visualizar recomendações do motorista (5 pontos)  
Eu como aluno solicitante da UVV, desejo visualizar as recomendações de um motorista que está me oferecendo carona. As recomendações e a quantidade de caronas oferecidas por este motorista deverão aparecer na mensagem de aceitar/recusar carona.
