### ISSUE TITLE
Inserir campo de complemento na tela de pedir carona e oferecer carona | Irineu

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#87]
Tirar o campo 'ponto de referência' do cadastro e colocar na tela pedir carona.
Trocar o nome do campo de 'ponto de referência' para 'complemento'.
Ao realizar o logoff, tirar a mensagem de "matricula e senha inválidas'.
Validar o campo email (garantir o @, por exemplo)
Tempo Estimado: 3 horas

**Comment by irineulemos** [comment]
Tempo gasto: 1 hora e 30 minutos.
