### ISSUE TITLE
Trazer o nome completo da rua no retorno na geolocalização | Lucas

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#88]
- Colocar o nome completo da rua no campo 'complemento'
- Atualizar nas telas de oferecer carona e histórico de caronas, os campos que exibem o endereço para a carona com o nome completo da rua.
- Deixar claro ao usuário que ele pode escolher informar sua localização pela geolocalização ou pelo autocomplete. Se for autocomplete, usar o campo complemento para informar um ponto de referência.
  Tempo Estimado: 5 horas

.

**Comment by irineulemos** [comment]
Tempo gasto: 1 hora e 30 minutos.
