### ISSUE TITLE
Criar Estórias de Exibição de Dados do Carro | Letícia

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#95]
Definir a estória para exibir os dados do carro do motorista nas telas:
     Pedir Carona: na mensagem de confirmação da carona que o solicitante recebe.
     Histórico de Carona: junto com as informações da carona aceita.

Tempo Estimado: 1 hora.

**Comment by lefernandesrocha** [comment]
estória criada.
Tempo gasto: 1h
