### ISSUE TITLE
Alterar Estórias de Cadastro, Pedir Carona e Histórico de Caronas |  Letícia

### ISSUE THREAD

**Issue by jessicaLPII** [Me-Leva/docs#96]
Definir estórias das telas que sofreram alterações:
      Cadastro de Usuário: retirar o campo 'Ponto de Referência'
      Pedir Carona: adicionar campo complemento para receber o endereço completo do solicitante.
      Histórico de Carona: adicionar às informações de carona aceita os dados do carro do motorista e o complemento.

Tempo Estimado: 1 hora.

**Comment by lefernandesrocha** [comment]
Estórias alteradas.
Tempo gasto: 1h
